version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      BACKEND_PORT: ${BACKEND_PORT:-4000}
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - FOR_DOCKER=1
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql-data:
